In [21]:


#Add Dependencies
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
import numpy as np

In [31]:
county_demo = "combined_csv.csv"
file_output = "../2019_County_data.csv"

In [23]:
# Import our input dataset
county_df = pd.read_csv(county_demo , dtype=str, low_memory=False, index_col=False, encoding="ISO-8859-1")

In [24]:
county_df

,SUMLEV,STATE,COUNTY,STNAME,CTYNAME,YEAR,POPESTIMATE,POPEST_MALE,POPEST_FEM,UNDER5_TOT,...,AGE7579_FEM,AGE8084_TOT,AGE8084_MALE,AGE8084_FEM,AGE85PLUS_TOT,AGE85PLUS_MALE,AGE85PLUS_FEM,MEDIAN_AGE_TOT,MEDIAN_AGE_MALE,MEDIAN_AGE_FEM
0,050,13,001,Georgia,Appling County,1,18236,9159,9077,1306,...,227,298,119,179,255,69,186,38.1,36.6,39.4
1,050,13,001,Georgia,Appling County,2,18238,9160,9078,1306,...,227,298,119,179,255,69,186,38.1,36.6,39.4
2,050,13,001,Georgia,Appling County,3,18334,9229,9105,1300,...,230,298,119,179,258,71,187,38.1,36.6,39.4
3,050,13,001,Georgia,Appling County,4,18459,9367,9092,1266,...,244,286,121,165,263,76,187,38.4,36.6,39.9
4,050,13,001,Georgia,Appling County,5,18385,9277,9108,1281,...,263,292,129,163,280,83,197,38.7,37.1,40.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37699,050,22,127,Louisiana,Winn Parish,8,14642,7816,6826,821,...,240,290,107,183,309,105,204,40.7,39.3,42.8
37700,050,22,127,Louisiana,Winn Parish,9,14532,7767,6765,824,...,243,307,127,180,319,102,217,40.6,39.3,42.9
37701,050,22,127,Louisiana,Winn Parish,10,14350,7647,6703,811,...,257,324,141,183,329,104,225,40.9,39.8,42.7
37702,050,22,127,Louisiana,Winn Parish,11,14138,7578,6560,830,...,266,327,147,180,337,102,235,41.1,39.7,43.3
37703,050,22,127,Louisiana,Winn Parish,12,13904,7447,6457,805,...,286,320,138,182,330,96,234,41.2,39.7,43.3

In [25]:
county_df = county_df.loc[county_df['YEAR'] == "12"]

In [26]:
columns_demo = ["STATE", "COUNTY", "STNAME", "CTYNAME", "POPESTIMATE", "POPEST_MALE", "POPEST_FEM", "MEDIAN_AGE_TOT", "MEDIAN_AGE_MALE", "MEDIAN_AGE_FEM" ]

In [27]:
countydemo_df=county_df[columns_demo]

In [28]:
countydemo_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3142 entries, 11 to 37703
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   STATE            3142 non-null   object
 1   COUNTY           3142 non-null   object
 2   STNAME           3142 non-null   object
 3   CTYNAME          3142 non-null   object
 4   POPESTIMATE      3142 non-null   object
 5   POPEST_MALE      3142 non-null   object
 6   POPEST_FEM       3142 non-null   object
 7   MEDIAN_AGE_TOT   3142 non-null   object
 8   MEDIAN_AGE_MALE  3142 non-null   object
 9   MEDIAN_AGE_FEM   3142 non-null   object
dtypes: object(10)
memory usage: 270.0+ KB

In [29]:
countydemo_df["FIPS"]= countydemo_df['STATE'] + countydemo_df['COUNTY']

In [30]:
countydemo_df

,STATE,COUNTY,STNAME,CTYNAME,POPESTIMATE,POPEST_MALE,POPEST_FEM,MEDIAN_AGE_TOT,MEDIAN_AGE_MALE,MEDIAN_AGE_FEM,FIPS
11,13,001,Georgia,Appling County,18386,9157,9229,39.7,37.9,41.2,13001
23,13,003,Georgia,Atkinson County,8165,4146,4019,36.6,35.9,37.4,13003
35,13,005,Georgia,Bacon County,11164,5455,5709,38.6,37.2,39.8,13005
47,13,007,Georgia,Baker County,3038,1494,1544,47.3,46.8,47.9,13007
59,13,009,Georgia,Baldwin County,44890,22737,22153,36.1,35.9,36.3,13009
...,...,...,...,...,...,...,...,...,...,...,...
37655,22,119,Louisiana,Webster Parish,38340,18685,19655,41.3,39.2,43.5,22119
37667,22,121,Louisiana,West Baton Rouge Parish,26465,13028,13437,36.8,35.8,37.8,22121
37679,22,123,Louisiana,West Carroll Parish,10830,5487,5343,40.8,38.6,43.2,22123
37691,22,125,Louisiana,West Feliciana Parish,15568,10114,5454,42.7,42.7,42.8,22125
37703,22,127,Louisiana,Winn Parish,13904,7447,6457,41.2,39.7,43.3,22127

In [32]:
#Export dataset to CSV
countydemo_df.to_csv(file_output)